### PR TITLE
Extend gemini 3b example and downgrade `wasmtime` so that tests will pass

### PR DESCRIPTION
**Pull request by i1i1**

### CODE REVIEW

**Review by ozgunozerk — COMMENTED** [review]
Ok I've made the same changes just 15 min ago and started test -> https://github.com/subspace/subspace-cli/actions/runs/3739925843/jobs/6347702169

will approve if these tests will check out

**Comment by ozgunozerk** [comment]
you should also change `wasmtime-types` in cargo lock @i1i1

**Comment by ozgunozerk** [comment]
Hmm, my tests also failed for windows... I guess it is not only `wasmtime` then.
The failing part is `windows`, and the `windows-sys` dependency for `wasmtime` does not change between `1.0.1` and `1.0.2`. So it kind of makes sense that it is still failing. 
However, I have no clue why is it not failing in monorepo then... 🤷

**Comment by i1i1** [comment]
I just copied `Cargo.lock` from monorepo. It should fix the issue as all dependencies are the same.

**Review by ozgunozerk — APPROVED** [review]

**Pull request merged**
